### ISSUE TITLE
esm2_t48_15B_UR50D out of memory

### ISSUE THREAD

**Issue by haonanzc** [mat10d/EvolvePro#11]
I tried to use esm2_t48_15B_UR50D on colab, it would be cut off automatically, this phenomenon also happened on my local PC. As esm2_t48_15B_UR50D is around 30GB, maybe the memory is not enough. Is there a way could solve this problem if my hardware resource is limitted?
![Uploading error.png…]()

**Comment by mat10d** [comment]
Yes, this is a limitation. To generate embeddings with limited resources can make the batch size smaller, and try to run this on your local system, but I do not think you can load the esm2 15B weights into colab RAM. Also see #8, and refer to the esm [repository](https://github.com/facebookresearch/esm) for more details on how to get esm embeddings.
