### ISSUE TITLE
FileNotFoundError when running scripts/process/exp_process.py due to missing t7_pol_n_mutants.xlsx

### ISSUE THREAD

**Issue by tspp520** [mat10d/EvolvePro#12]
I encountered a `FileNotFoundError` while running `scripts/process/exp_process.py`. The error message indicates that the file `/data/Bio_AI/EvolvePro/data/exp/n_mutant_dicts/t7_pol_n_mutants.xlsx` is missing. 

The specific error traceback is:
```plaintext
Traceback (most recent call last):
  File "/data/Bio_AI/EvolvePro/scripts/process/exp_process.py", line 56, in <module>
    generate_n_mutant_combinations(t7_pol_wt_fasta, t7_pol_mutant_file, n=2, output_file=t7_pol_2_output_file, threshold=1)
  File "/data/Bio_AI/EvolvePro/evolvepro/src/process.py", line 386, in generate_n_mutant_combinations
    mutants = pd.read_excel(mutant_file, header=None)
FileNotFoundError: [Errno 2] No such file or directory: '/data/Bio_AI/EvolvePro/data/exp/n_mutant_dicts/t7_pol_n_mutants.xlsx'
```

It seems that the function `generate_n_mutant_combinations` requires `t7_pol_n_mutants.xlsx` as an input, but this file is missing. Could you clarify:
1. How should this file be generated?
2. Is there a missing step in the script to create this file?
3. What should the file content/format be?

Thank you for your assistance!

**Comment by mat10d** [comment]
Hello, you can see the following: #7--this is a file that you would generate after a few rounds of evolution when you want to move from single mutants to multimutants.
