### ISSUE TITLE
No such file or directory: '../EvolvePro/data/exp/wt_fasta/t7_pol_WT.fasta'

### ISSUE THREAD

**Issue by Tang-WG** [mat10d/EvolvePro#17]
(evolvepro) del:~/Documents/Software/EvolvePro/scripts/process$ python exp_process.py 
Generating single amino acid mutants for t7_pol...
Traceback (most recent call last):
  File "/home/dell/Documents/Software/EvolvePro/scripts/process/exp_process.py", line 17, in <module>
    generate_wt(wt_sequences['t7_pol'], t7_pol_wt_fasta)
  File "/home/dell/Documents/Software/EvolvePro/evolvepro/src/process.py", line 335, in generate_wt
    with open(output_file, "w") as handle:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/dell/Documents/Software/EvolvePro/data/exp/wt_fasta/t7_pol_WT.fasta'

**Comment by mat10d** [comment]
We haven't yet added the proteins that we evolved ourselves to the repository. This is meant to be an example, based on this, you could evolve your own AA sequence of interest.
