### ISSUE TITLE
Questions About Certain Parts I Didn't Understand While Using the EvolvePro Tutorial

### ISSUE THREAD

**Issue by joelhys** [mat10d/EvolvePro#3]
I’m very excited about this fascinating and fancy tool, and I’m planning to apply it to the proteins I’m interested in. However, I have a few questions regarding its usage:

Regarding the initial set of 12 mutant variants provided, are these selected randomly? And does this mean I don’t need to perform actual biological experiments for these variants?

After running a round, I noticed the resulting file, df_sorted_all, contains a y_pred column as well as a y_actual column. What does the y_actual column represent? My understanding was that after running a round and identifying the top variants, I would need to experimentally test these variants biologically and then manually input the results in the y_actual column to compare them with the WT protein. However, in some cases, I found that the y_actual column was already filled in after running the program. Could you clarify how this is supposed to work?

Thank you in advance for your kind and detailed explanation!

**Comment by mat10d** [comment]
> Regarding the initial set of 12 mutant variants provided, are these selected randomly? And does this mean I don’t need to perform actual biological experiments for these variants?

For each round of EVOLVEpro, you need experimental measurements to pair with your selected variants. You can select your first round variants completely randomly, or select what you might hypothesize to be high activity variants. You then need to assay these to find out their actual activity, before using EVOLVEpro to suggest your next round of variants to assay.

> After running a round, I noticed the resulting file, df_sorted_all, contains a y_pred column as well as a y_actual column. What does the y_actual column represent?

The y_actual column is the activity value for the previously measured mutants, for which you have actual measurements for. This is just meant to show you how the top layer model is doing in predicting the activity for those that you have already measured, but for you next round, you would just work with the ones that you don't have measurements on.

I am assuming that you are using the colab notebook to run this? In that, we provided some example data to show you how round by round evolution works. But in reality, the `Round1.xlsx` file there is what you would generate in your real experimental work.

Thanks for using!
