### ISSUE TITLE
Request for DMS Data Sets

### ISSUE THREAD

**Issue by ld139** [mat10d/EvolvePro#4]
Dear authors,

Thank you for your great work! Could you please provide the 12 deep mutational scanning datasets mentioned in your paper, including mutation sequences and fitness scores? These would be very helpful for my research.

Best regards,
Ding Luo

**Comment by mat10d** [comment]
Please check the process [README](https://github.com/mat10d/EvolvePro/blob/main/scripts/process/README.md). We described where we got the DMS data. There actually may be a more updated version of the Livesey & Marsh paper that you should be able to easily retrieve.
