### ISSUE TITLE
Weighted Parameters in evolvepro

### ISSUE THREAD

**Issue by po99044** [mat10d/EvolvePro#6]
Thank you for your kind and detailed response earlier.

I wanted to ask for clarification regarding the possibility of incorporating weights into the parameters, such as expression level or affinity, as mentioned in your paper.

For example, if I wish to assign a weight to affinity that is four times higher than the weight for expression level, should I calculate this custom weighting criterion and directly input it into the activity column? Or would it be more appropriate to add an additional column to account for these weights?

Thank you again for your guidance and support.

Sincerely,
Gabriel

**Comment by mat10d** [comment]
Hello Gabriel. The model currently only optimizes on a single 'activity' vector. You can generate an activity vector from any type of weighting of the individual parameters that you are generating in your experimental assays. So yes, you would assign your weights as you'd like, generate an activity vector, and then plug that into the model. Let us know how it goes and good luck!
