### ISSUE TITLE
beneficial_mutations.xlsx

### ISSUE THREAD

**Issue by fire537** [mat10d/EvolvePro#7]
To generate n-mutant combinations:

```python
from evolvepro.src.process import generate_n_mutant_combinations
generate_n_mutant_combinations('output_path/dataset_WT.fasta', 'beneficial_mutations.xlsx', 3, 'output_path/dataset_3rd.fasta', threshold=1)

hi, 
Where is the beneficial_mutations.xlsx file?

**Comment by mat10d** [comment]
Hello, if you are generating n-mutant combinations after you have performed a few rounds of evolution of single mutants, you would generate a file that is similar to those generated in the rounds data [folder](https://github.com/mat10d/EvolvePro/tree/main/colab/rounds_data)--these essentially have a column for variant, and one for the activity.

**Comment by EasyPiPi** [comment]
Dear author,

I met the same issue, and while I tried to replace the "beneficial_mutations.xlsx" with the "kelsic_Round5.xlsx" under the colab/rounds_data directory, it prompted me an error:

` File "ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>' not supported between instances of 'str' and 'float'`

Do I misunderstand what you mean in your reply? An example file of beneficial_mutations.xlsx will help a lot for us to understand what is expected as an input.

Many thanks,
Yixin

**Comment by mat10d** [comment]
Thanks for this comment. I realized that the excel file expected by `generate_n_mutant_combinations` was one without a header. I have [updated](https://github.com/mat10d/EvolvePro/commit/f36a01e3ce089f15b1c14a7290fde5bba319d2e4) this to accept a standard file (like `kelsic_Round5.xlsx`) that has two columns--Variant and activity. This should work now.

**Comment by yueli8** [comment]
Dear Author,

I met the same issue.

My input fasta file is:
```
>WT Wild-type sequence
MNTINIAKNDFS
```
The error is:
```
>>> generate_n_mutant_combinations('output_path/dataset_WT.fasta', 'beneficial_mutations.xlsx', 3, 'output_path/dataset_3rd.fasta', threshold=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qinghuo/EvolvePro/evolvepro/src/process.py", line 393, in generate_n_mutant_combinations
    mutants['wt_aa'] = mutants.apply(lambda row: wt_sequence[int(row['position'])-1], axis=1)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qinghuo/miniconda3/envs/evolvepro/lib/python3.11/site-packages/pandas/core/frame.py", line 10374, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/qinghuo/miniconda3/envs/evolvepro/lib/python3.11/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/qinghuo/miniconda3/envs/evolvepro/lib/python3.11/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qinghuo/miniconda3/envs/evolvepro/lib/python3.11/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qinghuo/EvolvePro/evolvepro/src/process.py", line 393, in <lambda>
    mutants['wt_aa'] = mutants.apply(lambda row: wt_sequence[int(row['position'])-1], axis=1)
                                                 ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: string index out of range
```
Please see attached file of 'beneficial_mutation.xlsx'.

Thank you in advance for your great help!

Best,

Yue

[beneficial_mutations.xlsx](https://github.com/user-attachments/files/18621113/beneficial_mutations.xlsx)

**Comment by yueli8** [comment]
The beneficial_mutations.xlsx file can only have three mutations, not too much, such as 10 or 12 mutations.

Please see attached file.

[beneficial_mutations.xlsx](https://github.com/user-attachments/files/18627398/beneficial_mutations.xlsx)
